// <auto-generated />
using LOGINWEBAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Login.Migrations.FeedBackDb
{
    [DbContext(typeof(FeedBackDbContext))]
    [Migration("20240117092613_FeedBackContext")]
    partial class FeedBackContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LOGINWEBAPI.models.FeedBack", b =>
                {
                    b.Property<int>("SLno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLno"));

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedBackDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfCustomer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SLno");

                    b.ToTable("feedBacks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
